### PR TITLE
feat(data modeling): create product.weight component 

### LINKED ISSUE #14: feat(data modelling): Implementation of Product Weight Component with Associated Fields
I propose the creation of a product weight component along with associated fields based on product specifications within the table. The envisioned fields include:

- Package weight (numeric)
- Weight unit (select)
- Count per package (numeric)
- Item weight (numeric)
- Count per kg (numeric)
- Weight source (text)
- Log date (date)
- Notes (text)

Issue Goals:

- [ ] Develop the product.weight component.
- [ ] Integrate the product.weight component with the product item collection.
- [ ] Enable the linkage of multiple product.weight instances to a product item.

### PR DESCRIPTION
**Pull request by RitaDee**
Resolves #14 

Creates a Product.weight component.

### CODE REVIEW

**Comment by jtfairbank** [comment]
@RitaDee looks really good!  A few suggestions using [Conventional Comments](https://conventionalcomments.org/):

- praise: Everything is running fine when I tested it on GitPod!
- suggestion (blocking): Add explicit options to `weightUnit`.  The code we write later will only be able to handle known units, so we shouldn't let the admin / ops folks enter a unit that our code doesn't know how to handle.  If you select the `weightUnit` or `itemWeight` cell on the "product info" spreadsheet you should be able to see what units we currently support.
- nitpick: It might make sense to rename `weightUnit` to `packageWeightUnit` in order to explicitly tie it to the `packageWeight` field.  This is an improvement over the status quo.
- suggestion (non-blocking): It'd make sense to make `packageWeight`, `weightUnit`, `countPerPackage`, `weightSource`, and `logDate` required fields.  The others we can either calculate from the required fields, or are optional (such as `notes`).

**Comment by RitaDee** [comment]
> @RitaDee looks really good! A few suggestions using [Conventional Comments](https://conventionalcomments.org/):
> 
> * **praise:** Everything is running fine when I tested it on GitPod!
> * **suggestion (blocking):** Add explicit options to `weightUnit`.  The code we write later will only be able to handle known units, so we shouldn't let the admin / ops folks enter a unit that our code doesn't know how to handle.  If you select the `weightUnit` or `itemWeight` cell on the "product info" spreadsheet you should be able to see what units we currently support.
> * **nitpick:** It might make sense to rename `weightUnit` to `packageWeightUnit` in order to explicitly tie it to the `packageWeight` field.  This is an improvement over the status quo.
> * **suggestion (non-blocking):** It'd make sense to make `packageWeight`, `weightUnit`, `countPerPackage`, `weightSource`, and `logDate` required fields.  The others we can either calculate from the required fields, or are optional (such as `notes`).

Hey @jtfairbank,
* **praise**: Thank you for your detailed review! I've implemented the changes based on your suggestions.
* **note**: 
   - I've added explicit options to weightUnit to ensure compatibility. 
   - Renamed weightUnit to packageWeightUnit for better clarity and alignment with the packageWeight field.
   - Certain fields including packageWeight, weightUnit, countPerPackage, weightSource, and logDate are now required as suggested. 
 
Please let me know if there are any further adjustments needed.

**Comment by jtfairbank** [comment]
@RitaDee 

- **praise:** Changes look great!  I'll merge this in later today.
- **note:** I pushed a small commit to add metric units to `packageWeightUnit` as well.
- **nitpick:** You probably don't need to "quote-reply" in github comments unless there is a complicated issue / pr with many offshoot conversations.

Congrats on getting your first PR approved!! :partying_face:

**Review by jtfairbank — APPROVED** [review]

**Comment by jtfairbank** [comment]
@RitaDee so sorry for catching this at the last minute:

- **suggestion (blocking):** can we make `Product.Weight` a repeatable component in case we research multiple products and want to log the individual weights for each to average later?

**Comment by jtfairbank** [comment]
@RitaDee looks good!  We'll merge this in together at the session this evening in order to learn how to manage merge conflicts.

**Pull request merged**
