### PR TITLE
draft: add uniqueness check beforeCreate hook for needs model

### PR DESCRIPTION
**Pull request by swizzard**
## What changed?

Added `beforeCreate` hook for the `needs` model to ensure we're not creating duplicates per https://github.com/distributeaid/aggregated-public-information/issues/53.

## How can you test this?
- [ ] Attempt to create a `need` in the Strapi admin panel with the same item, region, subregion, survey, and need as a preexisting need in the database and ensure it reports an error and doesn't save the duplicate
- [ ] Attempt to create a `need` in the Strapi admin panel as above, but changing one value to be unique (e.g. the need id) and ensure no error is reported and the record is saved

### CODE REVIEW

**Comment by swizzard** [comment]
Having tested this locally, it doesn't seem to work at all. I'm going to leave it up but will have to revisit this, possibly during Wednesday or Thursday's coworking time.

**Comment by jtfairbank** [comment]
@swizzard good approach getting a draft PR up so we can review and discuss together at the cowork time!  I know that there are different hooks which are triggered when using the API vs. the CMS content manager to do CRUD operations, but I would think that DB lifecycle hooks apply to both.  @madcalf may have some insights here based on her previous backend work.

**Comment by madcalf** [comment]
👀

**Comment by madcalf** [comment]
Hey yeah there's a couple things I'm seeing here. 

1. Looks like you're trying both angles of adding lifecycle hooks. Actuallyl since `need.need` is a content-type that we've created, we can simply use a `beforeCreate` hook in the `src/api/needs-assessment/content-types/need/lifecycles.ts` file. We don't have to register any hooks in the bootstrap function and we don't need the `registerDbLifecycleHooks` file . (While this should technically work in that way, my understanding is that the `registerDbLifecycleHooks` approach is needed for content-types that Strapi creates (e.g. admin users, roles, permissions) and that we wouldn't have the models in our file structure to add a `lifecycles.ts` file for.  So for our purposes here the needs `lifecycles.ts file `is more appropriate.)

2. Regarding the duplicate lookup, Strapi recommends staying away from the lower level SQL operations in favor of their [Document Service API](https://docs.strapi.io/dev-docs/api/document-service) for queries because we get access to all the relations, components, validations, permissions, and other Strapi features. And if we did need to interact with the db at a lower level they also have the [Query Engine API](https://docs.strapi.io/dev-docs/api/query-engine). So either way we shouldn't need to get into the weeds of database connections and transactions.

I gamed out a version messing around with the Document Service API in [this branch](https://github.com/distributeaid/aggregated-public-information/pull/186) that seems to work with the queries.

**Comment by swizzard** [comment]
@madcalf after talking to @jtfairbank i'm going to close this branch and open a new one based on overriding the api controller.

**Pull request closed without merging**
