### PR TITLE
feat: create Financial.GDPConversions collection type

### PR DESCRIPTION
**Pull request by swizzard**
## What changed?

Created `Financial.GDPConversions` collection type.

## How can you test this?
I'm not entirely sure, beyond the Strapi Admin panel.

### CODE REVIEW

**Comment by ll-zerr** [comment]
@swizzard , looks good so far!! I did find a couple of things to review and address:

- **suggestion (non-blocking):** We probably want the `Country` and `Year` field-types to be required, ensuring each entry has them. (You can check this box off in the Advanced Settings for that field)
- **issue (blocking):** There are some missing currencies from the enum for the currency field (I count a total of 15 on the reference doc but see only 7 in the enum)
- **thought:** the `Ratio_US_to_Country` is a percentage in the reference doc, would an integer apply here versus a decimal? I don't do a lot of work in financial stuff, so I'm not entirely sure which one makes more sense for this number.

**Comment by swizzard** [comment]
@ll-zerr changes made per your comments. since all the values in the `Ratio US to country` column in the spreadsheet are whole numbers, changing the column type in strapi makes sense.

**Comment by ll-zerr** [comment]
@swizzard all changes look great! My bad for not catching this sooner:
**suggestion:** When testing an input, the year field type displays with a comma (X,XXX) instead of resembling a year. The same thing happened in the `Financial.CurrencyConversions` collection and the current solution was to create `year` as a text with regex and max value of 4. Probably should modify that to stay consistent. 
**thought:** We might want to add `country` as one of the fields displayed for entries in this collection in the Content Manager, it allows for a quick reference when seeing the entries.

**Comment by swizzard** [comment]
@ll-zerr i've made `Year` a string and added [the same regex `NeedsAssessment.Survey` uses](https://github.com/distributeaid/aggregated-public-information/blob/saga/src/api/needs-assessment/content-types/survey/schema.json#L13). I'm not sure where else we should be displaying that field, though.

**Comment by jtfairbank** [comment]
hey @swizzard was looking at this last night and think it's pretty much ready to merge in, just wanted to check up on a few things before i do.  will you be at one of the tech hangs this week?

**Comment by swizzard** [comment]
@jtfairbank I'm planning on attending tomorrow's.

**Comment by jtfairbank** [comment]
@swizzard awesome!  I'll see you there and we'll get this merged in. :smile:

**Review by jtfairbank — APPROVED** [review]
**Praise:** Awesome first PR @swizzard, glad to have this in there!

Adding in some notes from our review on the tech hang for posterity (all these are already addressed):

- **Suggestion:** Given the `year` regex, we don't actually need the max length field to be set.  Let's remove it from `NeedsAssessment.Survey` and `Financial.CurrencyConversion` content types for consistency.

- **Clarification:** Your instinct for making the `Ratio_US_to_Country` was correct!  It shows up on the Google Sheets page as a whole # percentage but that's just the view, the underlying data is still in decimal form.

- **Nitpick:** Couple of errant tab characters in the Currency values list to remove.

**Pull request merged**
