### PR TITLE
feat: update to node@22, generated types ordered alphabetically

### PR DESCRIPTION
**Pull request by jimthedev**
## What changed?

Bumps typescript-eslint to 8.15.0 due to [a breaking change](https://github.com/typescript-eslint/typescript-eslint/issues/10338).

Closes #169 

## How can you test this?

This is just a first PR from me. Trying to help so let me know if anything is out of line or needs adjusted. I just ran the readme steps and upgraded to node 22. In doing so it looks like generated types are now ordered alphabetically. If you want that in a separate PR let me know.

### CODE REVIEW

**Comment by jtfairbank** [comment]
@jimthedev looks solid!  I ran the automated upgrade on the frontend repo and it changed the Engines portion of `package.json` to `"node": ">=20.0.0 <=22.11.0"` so can we roll with that here as well for consistency?

I wouldn't worry about anything in the generated types file, we just checkin whatever it updates to.

Btw have you been added to our Contributors team?  We usually do branch-style PRs insted of fork-style PRs since that's easier for folks to collaborate with (checkout a new branch form the same origin instead of adding additional remote repos).

**Comment by jimthedev** [comment]
@jtfairbank Oh no I haven't done that yet. I will reach out properly and get some time set up to get properly onboarded so I can use that. I can also update this to use >=20.0.0 and then if we end up moving this to a branch it will contain the same range as the frontend. Thanks for taking a look.

**Comment by jtfairbank** [comment]
@jimthedev perfect, thanks!  You're in touch with @thegrumpyenby (Kai) for the onboarding right?  They'll be able to get you setup on everything. :smile:

**Comment by jimthedev** [comment]
@jtfairbank not yet but I sent an email over to the hello@ email so I am guessing that should kick off the process. I sort of circumventing it by ending up on the github before reaching out through the typical process. I have a lot to learn so it will be good to get all of the information that I am sure I need to read up on.

**Comment by jtfairbank** [comment]
Hey @thegrumpyenby Jim emailed us last night so I have his email now.  Will copy you in to get the onboarding going!

**Comment by jtfairbank** [comment]
hey @jimthedev good to see you on slack!  can you update the `engines` section of `package.json` to use `"node": ">=20.0.0 <=22.11.0"` for consistency with the frontend project and then i can get this merged?

**Comment by jimthedev** [comment]
@jtfairbank Yes! This should be ready to go now. There was [a bug](https://github.com/typescript-eslint/typescript-eslint/issues/10338) in typescript-eslint that was blocking the build. This PR fixes that by upgrading typescript-eslint. I updated engines as well. 

Also, this is currently coming from my fork. I think I have access now to move it to a branch if you prefer.

**Comment by jtfairbank** [comment]
@jimthedev sounds great!  And yeah if you could move it over to a branch that'd be very helpful, probably save me an hour mucking around in git.

**Comment by jimthedev** [comment]
Great! Closing this in favor of #198

**Pull request closed without merging**
